# config.py

# Gemini AI API key
GENIE_API_KEY = "AIzaSyDMXVLvuQOBRCGv6M5qJYUyYPHv1Z8sIz4"

# GNews.io API key
NEWSAPI_KEYS = [
    "4fec09d5becd42efbd6f474f2c540e18",
    "8554bc10e9c74502b31d866a3eb6bb4f",
    "c7a70174aab44b729ba51c4677f808c3"
]
NEWS_API_MODE = 'sequential'

# Stock universe: NIFTY 50 tickers
NIFTY_50_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'HINDUNILVR.NS',
    'BHARTIARTL.NS', 'ITC.NS', 'SBIN.NS', 'LICI.NS', 'HCLTECH.NS', 'KOTAKBANK.NS',
    'LT.NS', 'BAJFINANCE.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS',
    'SUNPHARMA.NS', 'TITAN.NS', 'WIPRO.NS', 'ULTRACEMCO.NS', 'ADANIENT.NS',
    'ONGC.NS', 'NTPC.NS', 'JSWSTEEL.NS', 'TATAMOTORS.NS', 'POWERGRID.NS',
    'BAJAJFINSV.NS', 'TATASTEEL.NS', 'COALINDIA.NS', 'INDUSINDBK.NS', 'HINDALCO.NS',
    'TECHM.NS', 'GRASIM.NS', 'ADANIPORTS.NS', 'BRITANNIA.NS', 'CIPLA.NS',
    'EICHERMOT.NS', 'DRREDDY.NS', 'NESTLEIND.NS', 'HEROMOTOCO.NS', 'BAJAJ-AUTO.NS',
    'BPCL.NS', 'SHREECEM.NS', 'TATACONSUM.NS', 'UPL.NS', 'APOLLOHOSP.NS', 'DIVISLAB.NS'
]

LARGE_CAP_MIN_MARKET_CAP = 100_000_000_000  # 100 billion INR
RSI_THRESHOLD = 50.0
EMA_PERIOD = 20
